export const accessToken: string =
    "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwibmFtZSI6ImpvYW8gdGVzdGUgMSIsImVtYWlsIjoidGVzdGVAdGVzdGUuY29tIiwiaWF0IjoxNjk5ODE4MTk5LCJleHAiOjE3MDA0MjI5OTksImF1ZCI6InVzZXJzIiwiaXNzIjoibG9naW4iLCJzdWIiOiI2In0.lSEDPphkYJVtvbo-4MHTkyi3CBInKzsu2ABw2plY2Ug";
